services:

  #monarc:
  #  ports:
  #    - 80:80
  #    - 443:443

  mariadb:
    image: mariadb:11.4
    environment:
      - MYSQL_ROOT_PASSWORD=demo
      - MYSQL_DATABASE=monarc
      - MYSQL_USER=monarc
      - MYSQL_PASSWORD=demo
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-pdemo"]
      interval: 10s
      retries: 20
      timeout: 5s
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
    driver: local
